# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71c76b13128aad1dcceba4492b997bc8599d1812b1754d7169f28af91a2fea0c7e7c5235b92033e6eefb75109e6ff7275c5fcc7e3b3ee3e142f77d3d76bd560c

test:
  secret_key_base: 05d4ae36828f5cb4f87b873d9a3806715215272f477825ab498ad2e67bacbc37a52c900cbd63f9fbaa9c6db6cfb8b9c746815c1b460f4e58610eeeb876eef02a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
